---
title: "Linear model"
subtitle: "Statistical programming with R"
author: "Summer School Utrecht"
params:
  answers: true
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: paper
    code_folding: hide
editor_options: 
  markdown: 
    wrap: 72
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = params$answers,
                      message = FALSE, 
                      warning = FALSE,
                      comment = NA)
```

------------------------------------------------------------------------

For this lab you need to load the packages `dplyr`, `ggplot2` and
`patchwork`.

```{r}
library(dplyr)
library(ggplot2)
```

# Data prepapartion

In this practical, we predict the `price` of diamonds of the `diamonds`
data from the `ggplot2` package. The data has 10 variables and 53940
observations. For that many cases it takes a long time to make a plot.
Therefore we reduce the size of the data a little bit.

a.  Set the seed to 100 and draw a random sample of 500 cases with
    `slice_sample()` function. Save this sample as `my_diamonds`

```{r}
set.seed(100)
my_diamonds <- slice_sample(diamonds, n = 500) 
```

b.  Because we want to work with dummy variable, we have to convert the
    variables of class `ordered` into variables of class `factor`. Do so
    and save the result.

```{r}
my_diamonds <- my_diamonds %>% 
  mutate(across(where(is.ordered), ~ factor(., ordered = F)))
```

# Simple regression

We start with a numeric predictor.

a.  Display a scatter plot with a linear regression line for the model
    `price ~ carat`.

```{r}
ggplot(my_diamonds, aes(x = carat, y = price)) +
  geom_point(size = 0.5) +
  geom_smooth(method = "lm", se = FALSE) 
```

b.  Display and interpret the summary of the model and interpret the
    effect of `carat` on `price`.

```{r}
fit <- lm(price ~ carat, my_diamonds)
summary(fit)
```

Now we use a categorical predictor.

c.  Plot the distribution of `price` as a function of the categorical
    variable `cut`.

```{r}
my_diamonds %>% 
    ggplot(aes(price, cut)) +
    geom_boxplot()
```

b.  Display and interpret the summary of the model with `cut` predicting
    `price`.

```{r}
lm(price ~ cut, my_diamonds) %>% summary()
```

# Multiple regression

a.  Display a scatter plot with a linear regression lines for the model
    `price ~ carat + cut`. Does the plot show evidence for interaction?

```{r}
ggplot(my_diamonds, aes(carat, price, col = cut)) + 
  geom_point() +
  geom_smooth(method = "lm", se = F) 
```

b.  Display the summary of the interaction model `price ~ carat * cut`,
    and interpret the parameter estimates.

```{r}
lm(price ~ carat * cut, my_diamonds) %>% summary()
```

c.  Perform an ANOVA test for the model main effects model and the
    interaction model. Which model fits the data best?

```{r}
anova(lm(price ~ carat + cut, my_diamonds),
      lm(price ~ carat * cut, my_diamonds))
```

We now add the numeric variable `depth` and the categorical variable
`color` as predictors of `price`.

d.  Perform an ANOVA test for by adding the variables `carat`, `cut`,
    `dpth` and `color` subsequently to the model. What do you conclude?

```{r}
anova(lm(price ~ carat, my_diamonds),
      lm(price ~ carat + cut, my_diamonds),
      lm(price ~ carat + cut + depth, my_diamonds),
      lm(price ~ carat + cut + depth + color, my_diamonds))
```

The `step()` function is specifically designed to find the best model
given a set of predictors.

e.  Apply the `step()` function to the main effects model with all four
    predictors.

```{r}
step(object = lm(price ~ 1, my_diamonds), 
     scope  = ~ carat + color + cut + depth)
```

f.  Perform a backward step-wise analysis with all main with the predictors `carat`, `color`, `cut`, and `depth`.

```{r}
step(lm(price ~ carat + cut + depth + color, my_diamonds))
```

g.  Display and interpret the summary this model.

```{r}
summary(lm(price ~ carat + cut + color, my_diamonds))
```

# Advanced

In the previous exercises we did not investigate potential interactions between the predictors.

a.  Use the `step()` function to find the best model when allowing for all pairwise interactions between the predictors. 

```{r}
step(lm(price ~ (carat + cut + depth + color)^2, my_diamonds))
```

b. There is one interaction term in the model. To interpret this interaction, display it a plot.

```{r}
ggplot(my_diamonds, aes(carat, price, col=color)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  theme_minimal()
```

------------------------------------------------------------------------

End of lab
