---
title: "Lab 4a"
subtitle: "Functional Programming"
author: 'Utrecht Summer School: Statistical Programming with R'
params:
  answers: true
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    code_folding: hide
editor_options: 
  markdown: 
    wrap: 72
---

```{r message=FALSE}
library(dplyr)
knitr::opts_chunk$set(eval=params$answers)
```

------------------------------------------------------------------------

# Function returning the cumulative sum of a vector

In this exercise you'll write your own cumulative sum function. This
function returns the cumulative sums of the elements of a vector, and
will work identically to the base R function `cumsum()`, e.g.

```{r eval=T}
cumsum(x = 1:4)
```

We'll take the following steps:

1.  Write the loop 2, Make container object
2.  Collect the results in a container object
3.  Embed 1 to 3 in the function `my_cumsum(x)`

But first make the vector `x` with the values `1:4`.

```{r}
x <- 1:4
```

a.  Now write a loop that computes the cumulative sums of `x`. This
    requires the following steps:

    1.  Define a `counter`, e.g. `i`
    2.  Define a `sequence` of integers that runs from 1 to the length
        of the vector `1:4`
    3.  The consecutive iterations should return the sum of `x[1:i]`
    4.  Use the `print()` command to print the outcome at each iteration

```{r}
for (i in 1:4) {
  
  print(sum(x[1:i]))
  
}
```

b.  Now make a container object. The most obvious would be to make it a
    numeric vector with length is `length(x)`. Check the help page of
    the function `numeric()` on how to do that.

```{r}
out <- numeric(length = length(x))
```

c.  Now rewrite the loop so that it stores the cumulative sums in the
    container vector. Run the loop and check the content of the
    container vector.

```{r}
for (i in 1:4) {
  
  out[i] <- sum(x[1:i])
  
}

out
```

d.  Now include the container object and the loop in your function
    `my_cumsum(x)`, where `x` is the function argument denoting the
    vector for which the cumulative sums have to be returned. Run the
    function, and check whether it appears in your workspace.

```{r}
my_cumsum <- function(x) {
  
  out <- numeric(length(x))
  
  for (i in 1:length(x)) {
    
     out[i] <- sum(x[1:i])
  }
  
  return(out)
}
```

b.  Apply your function to the vector `-4:4`, and compare its result to
    that of the base R function.

```{r}
cbind("my function" = my_cumsum(-4:4), "base R" = cumsum(-4:4))
```

# Display the scatter plots with `cyl` as dependent variable

In the lecture slides there is an example of a loop that returns scatter
plots with `mpg` as dependent variable and all other variables in
`mtcars` as predictor. In this exercise you write a loop that 
plots `cyl` on the y-axis and all other variable in `mtcars` on the x-axes.

a. Make an object `dv_pos` that takes the value of the position of `cyl` in `mtcars`.

```{r}
dv_pos <- 2
```

b. Make the object `sequence` for `i` that takes the values 1 to 11, but that skips the value of `dv_pos`.

```{r}
sequence <-(1:11)[-dv_pos]
```

c. Now copy-paste the code on the lecture slide "Adding the variable names". Change the sequence `2:11` in the object `sequence` you made in the previous exercise, and change the reference `1`  in the square brackets to `dv_pos`. Then run the loop to check if it works as intended.

```{r fig.asp=.35}
vars <- colnames(mtcars)
par(mfrow = c(2, 5), mar = c(4, 4, 1, 2))
for (i in sequence) {
  plot(x = mtcars[, i], y = mtcars[, dv_pos], xlab = vars[i], ylab = vars[dv_pos])
}
```

# Advanced

We will now write the function `plot_mtcars` with the argument `dv_pos` (without default) that makes the scatter plots for a dependent variable of the user's choice. Then we make it more general so that it can be applied to any data set.

a. Define the function with the expressions for `sequence`, `vars`, and the loop for making the plots. Run the function and check if it appears in your workspace.

```{r}
plot_mtcars <- function(dv_pos) {
  
  sequence <-(1:11)[-dv_pos]
  vars     <- colnames(mtcars)
  
  for (i in sequence) {
    plot(x = mtcars[, i], y = mtcars[, dv_pos], xlab = vars[i], ylab = vars[dv_pos])
    
  }
}
```

b. Now run the function with `dv_pos = 3` to check if it works. Place the `par(...)` statement before the function call to tell R how to position the plots. 

```{r fig.asp = .35}
par(mfrow = c(2, 5), mar = c(4, 4, 1, 2))
plot_mtcars(3)
```

c. To make this function applicable to any data set, change the name of the function `plot_mtcars` into `plot_dv`, add the argument `dataset` to it, and change the references to `mtcars` within the function to `dataset`.


```{r}
plot_dv <- function(dv_pos, dataset) {
  
  sequence <-(1:ncol(dataset))[-dv_pos]
  vars     <- colnames(dataset)
  
  for (i in sequence) {
    plot(x = dataset[, i], y = dataset[, dv_pos], xlab = vars[i], ylab = vars[dv_pos])
    
  }
}
```

b. Now load the package `MASS` into workspace, and try the function on the data set `UScrime` with the variable `y` (crime rate) on the y-axis. Adapt the `par(...)` statement to the number of variable in `UScrime`, and adapt `fig.asp`.

```{r fig.asp = .5, message=F}
library(MASS)
par(mfrow = c(3, 5), mar = c(4, 4, 1, 2))
plot_dv(16, MASS::UScrime)
```

------------------------------------------------------------------------

End of practical
